name             'weblogic'
maintainer       'Yuval Schwabe'
maintainer_email 'yuvalsc@gmail.com'
license          'fundtech'
description      'Installs/Configures weblogic Application Server 12.1.2'
version          '2.1.7'
depends          'compression'
depends          'oracle-inventory', '>= 0.2.0'
